### ISSUE TITLE
.deb includes .git repository

### ISSUE THREAD

**Issue by abackstrom** [svvitale/nxp-packaging#1]
I just downloaded this .deb from the NXP website, and it contained the .git directory for this repo. Not sure how affiliated you are with NXP, but this probably wasn't intentional. As is, the deb will install `/.git` and `/README.md`, as well as a few `.gitkeep` files scattered around.

**Comment by svvitale** [comment]
@michaelneurohr, you may want to repackage the reader library DEB and exclude the .git directory.  Thanks for the report, @abackstrom.
